services:
  mysql:
    image: mysql:8
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    # networks:
    #   - RestAPI-flexxus
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-P", "3306", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

# networks:
#   RestAPI-flexxus:
#     driver: bridge