-- Crear tabla LOCALIDADES
CREATE TABLE LOCALIDADES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LOCALIDAD VARCHAR(80),
    ACTIVO INT
) DEFAULT CHARSET=utf8mb4;

-- Crear tabla PUESTOS
CREATE TABLE PUESTOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PUESTO VARCHAR(80),
    ACTIVO INT
) DEFAULT CHARSET=utf8mb4;

-- Crear tabla DEPARTAMENTOS
CREATE TABLE DEPARTAMENTOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DENOMINACION VARCHAR(80),
    LOCALIDAD_ID INT,
    FOREIGN KEY (LOCALIDAD_ID) REFERENCES LOCALIDADES(ID)
) DEFAULT CHARSET=utf8mb4;

-- Crear tabla EMPLEADOS
CREATE TABLE EMPLEADOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRES VARCHAR(80),
    APELLIDO VARCHAR(80),
    EDAD INT,
    SUELDO DOUBLE,
    COMISION DOUBLE,
    FECHAALTA DATE,
    DEPARTAMENTO_ID INT,
    PUESTO_ID INT,
    FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTOS(ID),
    FOREIGN KEY (PUESTO_ID) REFERENCES PUESTOS(ID)
) DEFAULT CHARSET=utf8mb4;
